server:
  port: 8080
mysql:
  username: root
  password: 123456
  host: 192.168.2.11
  port: 3306
  database: short_url

redis:
  address: 192.168.2.11:6379
  database: 0
  password: 123456
short:
  prefix: http://localhost:8080
  length: 8


email:
  user:
  password:
  host : smtp.163.com
  port: 465
  toUser:


#


task-cron:
  #每5秒执行一次
  send-alarm-email: "*/5 * * * * *"
  agent-heartbeat-alarm: "*/5 * * * * *"
