server:
  port: 8080
mysql:
  username: root
  password: 123456
  host: 192.168.2.11
  port: 3306
  database: short_url

redis:
  address: 192.168.2.11:6379
  database: 0
  password: 123456
short:
  prefix: http://localhost:8080
  length: 8


email:
  user:
  password:
  host: smtp.qiye.163.com
  port: 465



task-cron: #每5秒执行一次
  send-alarm-email: "*/5 * * * * *"
  agent-heartbeat-alarm: "*/5 * * * * *"
  send-alarm-wx: "*/5 * * * * *"

# 告警通知给谁的邮件多个用;分割
alarm-email:
  cpu: guozhifengvip@163.com
  agent: guozhifengvip@163.com
  disk: guozhifengvip@163.com
  app: guozhifengvip@163.com

# 企业微信推送
alarm-weixin:
  # 用户账户
  toUser:
  # 部门Id
  toPartyId: fengzijk
  #
  agentId:
  #企业号的标识
  corpId:
  #企业号中的应用的Secret
  corpSecret: